### ISSUE TITLE
Different header styles, depending on category.

### ISSUE THREAD

**Issue by edgolub** [edgolub/medicover#1]
The navigation style for 'acitve' links is different for the second category when compared to the others in the design:
![image](https://cloud.githubusercontent.com/assets/9299435/13588630/83cfdef8-e4d1-11e5-857e-b09496cae8b4.png)

**Comment by edgolub** [comment]
I've used the second for all in this case, not sure which should be used. I don't think the second one is meaningful in any way.

**Comment by andrei-dn** [comment]
I am not sure I understand what you are referring to, but the font is only Humanist 777 for the title in the menus and for the rest of the menus.

**Comment by andrei-dn** [comment]
one more comment regarding menu fonts: on the second sub menu (Berlin Mitte, Bochum, etc.), the font is not clear, like for Medicover Praxis.
<img width="345" alt="bildschirmfoto 2016-03-08 um 13 09 47" src="https://cloud.githubusercontent.com/assets/17672928/13601344/b4ca7a6e-e52f-11e5-809e-90a07275a038.png">

**Comment by andrei-dn** [comment]
I just saw that you didn't receive the humanist777 in the package, I am uploading it now

**Comment by andrei-dn** [comment]
For slogans and Body titles, we are using the giorgio font, for menu and normal text, we are using the humanist777 font

**Comment by andrei-dn** [comment]
examples:
![fonts example giorgio](https://cloud.githubusercontent.com/assets/17672928/13601803/01d141f0-e533-11e5-95d3-d9542fb89fed.jpg)
![humanist777 example](https://cloud.githubusercontent.com/assets/17672928/13601804/01d72be2-e533-11e5-9902-3ae222828c38.jpg)
