### ISSUE TITLE
Homepage issues

### ISSUE THREAD

**Issue by andrei-dn** [edgolub/medicover#5]
1. The picture is not showing the hands from the second person and because it's a bit larger on the top, it focuses on the breast area, which we don't want :) I pasted below how it looks in our file:
<img width="440" alt="bildschirmfoto 2016-03-08 um 15 00 40" src="https://cloud.githubusercontent.com/assets/17672928/13603601/b642bb0e-e53e-11e5-9382-045fa74365c7.png">

**Comment by andrei-dn** [comment]
2. The blue ribbon on the bottom can be smaller (not a priority for tomorrow)
<img width="894" alt="bildschirmfoto 2016-03-08 um 15 03 21" src="https://cloud.githubusercontent.com/assets/17672928/13603631/efcb17fe-e53e-11e5-9776-406a66ea4aa8.png">

**Comment by edgolub** [comment]
That's because I'm cropping the image based on the browser size, as you can see here:
![image](https://cloud.githubusercontent.com/assets/9299435/13605664/f66d7598-e548-11e5-92ac-343bb4f18391.png)
