### ISSUE TITLE
Menu color for Standorte

### ISSUE THREAD

**Issue by andrei-dn** [edgolub/medicover#6]
For the Standorte menu, we used the Pantone 285, CMYK 89/43/0/0, the one you have is a lot darker, please update to this one.

**Comment by edgolub** [comment]
Yes, but that is a CMYK color as it says. Web Browsers only understand HEX, RGB, and the newest HSL. Aside from that, I've also used a different color, my bad.

I've updated it with the proper HEX value. Sometimes color loss is possible when using the hex value of a CMYK color. If so let me know, and we can try to find one as close to the one you want as possible.
