### ISSUE TITLE
Menu should remain sticky altogether even when scrolling

### ISSUE THREAD

**Issue by andrei-dn** [edgolub/medicover#8]
When we click on a page, we show the chosen subpage in the menu, but once we start scrolling, this disappears. Please make it sticky all the time. This should be fixed for tomorrow.

**Comment by andrei-dn** [comment]
<img width="758" alt="bildschirmfoto 2016-03-08 um 15 21 50" src="https://cloud.githubusercontent.com/assets/17672928/13604112/870e55ca-e541-11e5-99a9-94125d980d69.png">
The endocrinologie should stay even when we scroll
<img width="1440" alt="bildschirmfoto 2016-03-08 um 15 23 02" src="https://cloud.githubusercontent.com/assets/17672928/13604142/ac05caac-e541-11e5-987e-389d9903b6e7.png">

**Comment by edgolub** [comment]
No issue...
